name: CI/CD Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # Fallback to explicitly install pytest

      - name: Debug Python and Pip Versions
        run: |
          python --version
          pip --version

      - name: Check pytest installation
        run: |
          pip show pytest
          which pytest

      - name: Run tests
        run: python -m pytest  # Use python -m to avoid PATH issues
